
#ifndef AUTOACCOUNTING_STARTER_H
#define AUTOACCOUNTING_STARTER_H

#define PID_FILE "daemon.pid"

#define TOO_MATCH_CONNECTIONS_ERROR  99
#define BIND_ADDRESS_ERROR  98
#define LOG_FILE_TOO_LARGE  97
#define FORK_CHILD_ERROR 1
#endif
